# ca gateway for exposing container network PVs to the host's loopback interface

services:

  # ca-gateway for test / dev ##################################################

  ca-gateway: &ca-gateway

    container_name: ca-gateway

    image: ghcr.io/epics-containers/docker-ca-gateway:2.1.3ec1

    expose:
      - 5064-5065/udp
      - 5064-5065

    ports:
      # bind to localhost to isolate channel access to this host only
      - 127.0.0.1:5064:5064/udp
      - 127.0.0.1:5064-5065:5064-5065

    restart: unless-stopped

    networks:
      channel_access_devcontainer:

    configs:
      - source: ca-gateway_config
        target: /config

    command: -cip 170.21.255.255 -pvlist /config/pvlist -access /config/access -log /dev/stdout -debug 1

    profiles:
      - test
      - dev

  # debugging version of gateway container #####################################
  ca-gateway-debug:

    <<: *ca-gateway

    # this image is not distroless and has network tools installed
    image: ghcr.io/epics-containers/docker-ca-gateway-debug:2.1.3ec1

    profiles:
      - debug

configs:
  ca-gateway_config:
    file: ./config

networks:
  channel_access_devcontainer:
    external: true